### ISSUE TITLE
XF 2.3.1.114 Support?

### ISSUE THREAD

**Issue by adamlonsdale** [keannan5390/Xamarin.Plugin.FAB#10]
Is 2.3.1.114 Xamarin.Forms supported by the FAB? I have a new project with your XAML Sample and whilst the buttons appear - the FAB does not. I've added the resources in (plus.png) as well as the XAML and even tried referencing 2.1.2-pre3 to no avail.

Should mention this is iOS.

**Comment by ghost** [comment]
this is likely the same reasoning described in #13.

closing this issue.
