### ISSUE TITLE
Added support for retina screen on iOS

### ISSUE THREAD

**Issue by lanarchyste** [keannan5390/Xamarin.Plugin.FAB#18]
The picture is little blurred on retina screens.
It's posible to correct this easily.

In the `FloatingActionButtonRenderer.cs` file, at line 151, replace the following line : 

`UIGraphics.BeginImageContext(new CoreGraphics.CGSize(widthRequest, heightRequest));`

by

`UIGraphics.BeginImageContextWithOptions(new CoreGraphics.CGSize(widthRequest, heightRequest), false, UIScreen.MainScreen.Scale);`

**Comment by imuller** [comment]
Any solution for this?

**Comment by dylanreid** [comment]
Please merge lanarchyste's solution - very simple and the current version looks extremely unprofessional

**Comment by ghost** [comment]
this is completed. available in version [2.2.0-pre1](https://www.nuget.org/packages/FAB.Forms/2.2.0-pre1).

I'd appreciate verification in other solutions before I bump the package out of a prerelease state.

**Comment by lanarchyste** [comment]
Hi,

I just tested on my project Xamarin Android and iOS, the display on iOS is well corrected and I have no regression.

Thank you very much !
