### ISSUE TITLE
Button not visible on iOS in Release mode (device)

### ISSUE THREAD

**Issue by Adam-Langley** [keannan5390/Xamarin.Plugin.FAB#3]
Under the specific scenario of building Release mode, and running on a physical device, the button is not visible.
I discovered this when publishing to TestFlight.
Disabling the linker fixes the issue - I cannot find which assemblies to exclude from the linker to get it to work.

Very odd, because "Links SDK Assemblies Only" does not cause a problem when building in Debug mode, only in Release mode.

I have excluded all of these, to no avail:
- FAB.iOS 
- FAB.Forms
- Xamarin.Forms.Platform.iOS
- Xamarin.Forms.Platform
- Xamarin.Forms.Core
- Xamarin.Forms.Xaml

**Comment by Adam-Langley** [comment]
I've tracked this down a little further. The issue arises SPECIFICALLY when "Enable Device Specific Builds" (iOS Build tab in Project Properties) is UNTICKED - which is the default configuration for Release mode.
Still trying to figure out what is going on as a result of this option that is breaking this library.

note: I have added the MNFloatingActionButton directly to an iOS Release/device project, and it appears fine - so the breaking is in the Xamarin Forms realm...

**Comment by Adam-Langley** [comment]
Ok... a little more info....

My device is an iPhone 6+, so enabling "Device Specific Builds" will only build the 64-bit binary. Disabling it should (in theory) build 32 and 64 bit. So, I figured... what if I disabled it (which causes the issue), BUT force my App to ARMv7 only (32bit)... that should build the 32bit binary only.... and perhaps it will work again?

Yep - it then works. 

Where we're at: If the App executes in 64-bit mode, the FAB button will not appear.
Hopefully I can use this information to track it down a little further.

**Comment by Adam-Langley** [comment]
OK - simple solution. 
I had put [Preserve] on the actual renderer, but it didn't work. The following does work.

```
[Preserve(AllMembers = true)]
public class LinkerPleaseInclude
{
    public void Include(FloatingActionButtonRenderer renderer)
    {
        new FloatingActionButtonRenderer();
    }
}
```

**Comment by ghost** [comment]
@nimble99 thanks for tracking down, i'm waiting for a PR to be updated, when i build that for nuget i'll include this as well.

**Comment by ghost** [comment]
@nimble99 this available in the 2.1.2-pre3 package. I need to do some final testing. I don't have your device so I couldn't test for sure.

**Comment by ChandrasekarM** [comment]
Hi, 
I still facing this issue. Is it really working in iOS with 2.1.2-pre3 package?

**Comment by markradacz** [comment]
unfortunately just tested 2.1.2-pre3 package with iOS 10.2 (14C92) version and it's still not visible in Release mode
